### ISSUE TITLE
improve code coverage of LocalDateTimeServiceImpl in pandora-calculation

### ISSUE THREAD

**Issue by WJ-van-Hoek** [WJ-van-Hoek/PANDORA#112]
https://app.codecov.io/gh/WJ-van-Hoek/PANDORA/blob/master/pandora-calculation%2Fsrc%2Fmain%2Fjava%2Fcom%2Fscience%2Fearth%2Fbiogeochemistry%2Ffreshwaters%2Fpandora%2Fgeneral%2Fservices%2Fcalculation%2Fimplementations%2FLocalDateTimeServiceImpl.java

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  working on this as well... This seems that I can proceed without checking often in circleCI and CodeCov😁.  because for issue #119 i had to check often in codeCov in order to keep track of the progress.. Since CircleCI is having issue , for now I can locally do this change and keep it updated in my branch by the time you are done with the fix from your Utils repo .. I will continue with codeCove analysis after that for both the coverage issue. Thanks

**Comment by WJ-van-Hoek** [comment]
@tamojitdas fyi, you can run mvn clean install in pandora-calculation directory and then check directory pandora-calculation/target/site to locally see an updated code coverage. Just make sure you don't commit the stuff in the target directory.

**Comment by WJ-van-Hoek** [comment]
@tamojitdas  I am working on at this very moment, I expect to merge a PANDORA PR in a few minutes. If you pull the latest master you will be able to run on circle ci again

**Comment by WJ-van-Hoek** [comment]
@tamojitdas if you now pull the latest master in your PANDORA branch, the CircleCI build should succeed

**Comment by tamojitdas** [comment]
Thanks @WJ-van-Hoek for the fix and really no worries for the time taken, there was no delay at all..I ll continue with my work then ...and. Will try to wrap this up by today or tomorrow..

**Comment by WJ-van-Hoek** [comment]
> Thanks @WJ-van-Hoek for the fix and really no worries for the time taken, there was no delay at all..I ll continue with my work then ...and. Will try to wrap this up by today or tomorrow..

@tamojitdas before you continue working on this I suggest to pull in the latest PANDORA master.
I updated some dependencies in the pom. Let me know if you face new issues; glad to help.

**Comment by tamojitdas** [comment]
Sure

**Comment by tamojitdas** [comment]
com.general:spring-parent-pom:pom:0.0.3 seems to be absent ...getting errors in CircleCI build logs ..Please Check.... Thanks.

**Comment by WJ-van-Hoek** [comment]
> @WJ-van-Hoek  com.general:spring-parent-pom:pom:0.0.3 seems to be absent ...getting errors in CircleCI build logs ..Please Check.... Thanks.

Thanks, on it atm

**Comment by WJ-van-Hoek** [comment]
@tamojitdas: fixed, a token expired

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek, Code Coverage is 100% now for this class

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  let me know for any changes to be done in my PR. Thanks.

**Comment by WJ-van-Hoek** [comment]
Hi @tamojitdas ,I appreciate your work and effort. These days unfortunately I have no chance to work on my personal projects. I haven't been able to look at your pr and it is possible I won't be for the coming week. As soon as I am available for my github projects, I will review it (high on my prio list)

**Comment by tamojitdas** [comment]
That's Understandable @WJ-van-Hoek  ....no worries.

**Comment by WJ-van-Hoek** [comment]
> Hi @WJ-van-Hoek I see you have updated the master ...I will sync my branch branch with main after I return from Office... and Let me know about the Review.

Yes, i just updated the master with an image of how I want to develop the architecture to add some quality to the application. Should not be in the way of your contribution.

Regarding your PR, i need to have a thorough look at that as I saw there were a lot of changes. Although the added code changes may have achieved the objective of reaching 100% code coverage for the requested class; a lot of redundant LoC were added. 

Without going into too much detail now, a hint is that I can give for now is that I would like to have a unit test that only touches the LocalDateTimeServiceImpl, nothing else.

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  can you take a look on PR #138 I have done the requested Changes and Re-requested for you to review. Let me know if any further chnages need to be done.

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  is this issue still looked at.

**Comment by WJ-van-Hoek** [comment]
> Hi @WJ-van-Hoek  is this issue still looked at.

@tamojitdas yes, it will be looked at but not now. I expect to have time for my github projects next week Sunday. Take care and wish you all the best in 2024!🎆

**Comment by tamojitdas** [comment]
Happy New Year @WJ-van-Hoek, wishing you a great new Year's Eve and a wonderful year ahead...

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  let me know if you are available this weekend for reviewing 
my changes
