### ISSUE TITLE
improve code coverage of CellTimestepServiceImpl in pandora-calculation

### ISSUE THREAD

**Issue by WJ-van-Hoek** [WJ-van-Hoek/PANDORA#119]
https://app.codecov.io/gh/WJ-van-Hoek/PANDORA/blob/master/pandora-calculation%2Fsrc%2Fmain%2Fjava%2Fcom%2Fscience%2Fearth%2Fbiogeochemistry%2Ffreshwaters%2Fpandora%2Fgeneral%2Fservices%2Fcalculation%2Fimplementations%2FCellTimestepServiceImpl.java

**Comment by tamojitdas** [comment]
Hi, can I work on this. I've forked your code and made the initial setup. Currently working on the new test cases for CellTimestepService.java. I am also new to open souce.

**Comment by WJ-van-Hoek** [comment]
hi @tamojitdas, appreciate you are taking a look into the repository!

I strongly would enjoy if you would make a clone instead of a fork.
A general suggestion for the overview of the repo, its branches and related ticket is to name your branch after the ticket; in this case PANDORA-119.

Once you feel confident you can make a PR to the master.

Once again, appreciate your time and effort. If you have questions or any other request, I am trying to answer as quickly as possible.
best

**Comment by tamojitdas** [comment]
Sure will do that

**Comment by tamojitdas** [comment]
I guess I need to added as a collaborator in order to create a feature branch from master.

**Comment by WJ-van-Hoek** [comment]
@tamojitdas  ok, I am also new to open source managing a repo, so thank you for letting me know.

This friday I hope I have time to come up with a bit of an OS guideline for the repo.

**Comment by tamojitdas** [comment]
Sure Thanks...So Just Conforming CodeCov will work on feature branch also right??

**Comment by WJ-van-Hoek** [comment]
CodeCov works on both feature and master, yes. However, you might need a key to run a pushed commit in CircleCI for the use of dependencies from another GitHub repo. I hope I can be online later today (in around 12 hours) to help you with that.

**Comment by tamojitdas** [comment]
you mean the token in settings.xml under .circleci?

**Comment by WJ-van-Hoek** [comment]
Yes, I think I have to provide a token for read access from your circle ci account (free) to my utils repository. Maybe not, you could try to push a random change in a new branch named PANDORA-119 and see if it is able to build

**Comment by tamojitdas** [comment]
Yup build is happening in circleCI

**Comment by tamojitdas** [comment]
And also the branch came under codeCov. Thanks Man

**Comment by tamojitdas** [comment]
HI @WJ-van-Hoek  the docker.utils is no more being recognised in circleCi ....when i  looked through the Pom of your general.utils repo the version for docker.utils artifact is missing.. Can you take a look. Thanks

**Comment by WJ-van-Hoek** [comment]
Thanks for letting me know. Yes, I messed something up earlier today. I removed a release of the utils from another repository. I am not available at this moment, aim to fix it later today. Approximately 6 hrs from now.  Again, appreciate your work and patience!

**Comment by tamojitdas** [comment]
Code coverage increased to 100 % for this class

**Comment by WJ-van-Hoek** [comment]
> Code coverage increased to 100 % for this class

Whoop whoop, make a PR to master and I will review

**Comment by tamojitdas** [comment]
HI @WJ-van-Hoek  Created the PR https://github.com/WJ-van-Hoek/PANDORA/pull/132 .. Pls check and let me know if I need to update something.

**Comment by tamojitdas** [comment]
Hi @WJ-van-Hoek  let me know if there is any update for the PR review

**Comment by WJ-van-Hoek** [comment]
No update, have no time to look at personal projects so far. Hopefully in the weekend. Thanks for your patience.
